version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: lifequest-db
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: lifequest
      POSTGRES_PASSWORD: lifequest_secret
      POSTGRES_DB: lifequest
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
